### ISSUE TITLE
Bugs Relating to Portal Gates (Block not Item)

### ISSUE THREAD

**Issue by MrCreeps** [northwesttrees-gaming/PortalGates#3]
Placing a Portal Gate will break all blocks around it even if they are unbreakable (End Portal Frames, Portal Gate Slabs and Steps, etc)

Placing a Portal Gate when Bedrock is contacting the Portal Gate block, will cause the other 2 blocks that would be next to the bedrock to not be generated, however if the bedrock is not touching the Portal Gate block, it will generate the other 2 blocks (stairs and slab) in the correct places.

Stand-alone Portal Gate Steps will be removed only on a block update unless they are placed next to a Portal Gate block, while Portal Gate Slabs are automatically removed even if they are placed next to a Portal Gate Steps block. 

Portal Gate Steps and Slabs do not render properly in the hand and in the inventory (Probably just be because they aren't meant to be obtained but they look really nice as building blocks especially the steps as they can be used as stairs.)

Having access to unbreakable blocks in survival (Portal Gate Slabs and Steps) means you can softlock yourself (it does take quite a bit of effort to place Portal Gates in a way that you are trapped but I was able to do it multiple times)

Overall I feel the only thing that really needs to be fixed is that it can break all blocks except bedrock as the other ones are not really possible in survival mode and without deliberately trying to break it :P

**Comment by northwesttreesgaming** [comment]
> Placing a Portal Gate will break all blocks around it even if they are unbreakable (End Portal Frames, Portal Gate Slabs and Steps, etc)
This might be able to be fixed if I check if only replaceable blocks are in the area instead of testing for unbreakable ones. It may also fix the issue below too.

> Placing a Portal Gate when Bedrock is contacting the Portal Gate block, will cause the other 2 blocks that would be next to the bedrock to not be generated, however if the bedrock is not touching the Portal Gate block, it will generate the other 2 blocks (stairs and slab) in the correct places.

This was designed to do that due to blocks being in a way that is not obtainable.
I will try to figure out a workaround for placement in the patch I am now working on.

> Portal Gate Steps and Slabs do not render properly in the hand and in the inventory (Probably just be because they aren't meant to be obtained but they look really nice as building blocks especially the steps as they can be used as stairs.)

I noticed that mcreator did not make a 3d block I am not sure if this is on blockbench's side or MCreator's but I will try to address this issue in the patch.

> Having access to unbreakable blocks in survival (Portal Gate Slabs and Steps) means you can softlock yourself (it does take quite a bit of effort to place Portal Gates in a way that you are trapped but I was able to do it multiple times)

I did not even think that nice catch, I will tweak some of the properties for the block to make them not obtainable unless through creative mode.

> Overall I feel the only thing that really needs to be fixed is that it can break all blocks except bedrock as the other ones are not really possible in survival mode and without deliberately trying to break it

Again some settings will be tweaked I will also make sure that the blocks are only removed when the portal gate block is broken if they are located there this should allow for use in creative mode if it's not testing on the slabs and stair blocks side of things.

Thank you very much for your insight you caught a lot of issues I will work on those right now so I can get a patch out in the next day or two.

**Comment by northwesttreesgaming** [comment]
All Issues here should now be fixed, I also made some other minor changes that fixed some other issues I was aware of but could not figure out at the time. I will release the patch shortly. I just need to get things in order before I do so.

Again thank you for reporting the issue 😊

**Comment by MrCreeps** [comment]
Thanks for fixing the issues, I can make very nice staircases now :)

I have experienced some other weird things relating to teleporting long distances (300 blocks worked fine but 600 didn’t. Also these were in the 1.0.0 version, not the patch, so I haven’t tested that yet) but I haven’t found time to test it extensively in any version, so I won’t make an issue yet until I can provide more details about it.
